## Przykladowe uklady rownan

In [5]:
import numpy as np

In [15]:
A = np.matrix([[3.0, 2.0],
               [-1.0, 4.0]])

b = np.matrix([3.0, 1.0]).transpose()

x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[[0.71428571]
 [0.42857143]]


True

In [16]:
A = np.matrix([[5.0, 2.0, 1.0],
               [-3.0, 10.0, 4.0],
               [20.0, -3.0, 30.0]
              ])

b = np.matrix([1.0, 2.0, 3.0]).transpose()

x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[[0.10532475]
 [0.21123464]
 [0.05090696]]


True

In [17]:
A = np.matrix([[13.5, 5.3, -3.9],
               [2.9, 7.1, 1.7],
               [1.1, -4.7, 8.1]
              ])

b = np.matrix([3.5, 9.7, 1.7]).transpose()

x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[[0.0621367 ]
 [1.13490999]
 [0.85996625]]


True

In [18]:
A = np.matrix([[10.23, 2.21, 3.54],
               [3.69, 15.72, 8.13],
               [-6.93, 1.45, 12.12]
              ])

b = np.matrix([12.67, 8.74, 7.5]).transpose()

x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[[ 0.89204135]
 [-0.25287977]
 [ 1.159119  ]]


True

In [21]:
A = np.matrix([[80.801, -7.4319, 43.6892, 1.0001],
               [6.3159, -100.101,  32.135, -57.985],
               [-6.3873, -10.555,  54.43, 22.19],
               [5.32, -8.234,  -10.345, 46.4343]])

b = np.matrix([19.1508, 65.1693, 1.9015, 100.31]).transpose()

x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[[ 0.53554466]
 [-1.81857002]
 [-0.89756246]
 [ 1.57645347]]


True

In [22]:
A = np.matrix([[-61.302, 9.3913, 13.8632, 20.2358],
               [14.2962, 94.216,  -26.331, 33.8251],
               [6.8313, -5.777,  -24.131, -10.139],
               [-7.1, 29.741,  -8.918, 56.9661]])

b = np.matrix([291.1081, -40.2311, -78.5455, 62.132]).transpose()

x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[[-4.08450234]
 [ 0.45597077]
 [ 1.73128357]
 [ 0.61458646]]


True

In [24]:
A = np.matrix([[43.01, 5.002, -23.112, 0.9201],
               [-17.734, 57.101,  -21.531, -4.445],
               [-11.1012, 16.761,  -61.7489, 20.1309],
               [-19.993, 42.131,  31.6329, 123.123]])

b = np.matrix([1.1111, 2.2222, 3.3333, 4.4444]).transpose()

x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[[ 0.00287457]
 [ 0.02939317]
 [-0.0349511 ]
 [ 0.03548575]]


True

In [26]:
A = np.matrix([[235.167, -57.439, 17.0921, -138.7552, 5.2057],
               [-25.3271, 87.9536,  11.3692, 6.4365, -21.1269],
               [-13.3378, -37.179,  -91.382, -11.9683, 6.9215],
               [1.593, -2.1479,  -14.6703, 38.4833, -8.7849],
               [0.5493, -103.275,  53.684, -83.9674, 341.683]
              ])

b = np.matrix([3.012, 78.3318, 59.4835, 1265.315, 363.19]).transpose()

x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[[ 21.3344624 ]
 [  9.29122727]
 [-10.66376885]
 [ 31.47387947]
 [ 13.24700401]]


True